// See https://svelte.dev/docs/kit/types#app.d.ts
// Env is generated by `pnpm cf:types` (wrangler types) into worker-configuration.d.ts.

import type { createAuth } from '$lib/server/auth';

declare global {
	namespace App {
		interface Locals {
			auth: ReturnType<typeof createAuth>;
		}
		interface Platform {
			env: Env;
			cf: CfProperties;
			ctx: ExecutionContext;
		}
	}
}

export {};
