<script lang="ts">
	// One head block for every marketing page, because four hand-written ones drift:
	// three of them had no description at all, none declared a canonical, and the
	// product name was retyped in each title.
	//
	// The canonical matters more here than it normally would. This domain had a
	// previous occupant, and Google's own report still names a Brazilian site as the
	// canonical it picked for our homepage — a duplicate verdict formed while the
	// domain was parked. An explicit self-canonical on every page is what withdraws
	// that guess, and it drops the query string, so ?lang=fr does not read as a
	// second page competing with the first.
	//
	// The positive robots value is not normally worth writing, since absence means
	// index. It is written here because the last crawl of this domain found a
	// noindex on the parked page, and one line removes any doubt on the next one.
	import { page } from '$app/state';
	import { i18n } from '$lib/i18n/index.svelte';
	import { CANONICAL_ORIGIN } from '$lib/links';

	let {
		title,
		description,
		/** Schema.org payload for this page, emitted as JSON-LD. */
		jsonLd
	}: { title?: string; description: string; jsonLd?: unknown } = $props();

	// The name lives in the tab, which is one of the two places it is allowed to
	// appear at all. Never inside a sentence.
	const heading = $derived(title ? `${title} · Regeste` : 'Regeste');
	const canonical = $derived(`${CANONICAL_ORIGIN}${page.url.pathname}`);

	// The same page in the other language, declared both ways plus x-default, which
	// is what tells Google these are translations rather than duplicates. It could
	// not be said before: the locale was a query parameter the canonical dropped, so
	// every French URL folded into its English twin and only one language existed as
	// far as search was concerned.
	const rest = $derived(page.url.pathname.replace(/^\/fr(?=\/|$)/, '') || '/');
	const enHref = $derived(`${CANONICAL_ORIGIN}${rest}`);
	const frHref = $derived(`${CANONICAL_ORIGIN}/fr${rest === '/' ? '' : rest}`);

	// The whole tag is assembled here rather than in the markup: a literal <script>
	// inside a template string in the template is what the svelte eslint parser
	// chokes on, and the closing tag has to be written broken so the HTML parser
	// does not end the component's own script block on it.
	//
	// Escaping `<` in the payload is what keeps a dictionary string from closing the
	// tag it is being written into. \u003c is valid JSON and parses back to `<`.
	const ld = $derived(
		jsonLd
			? '<' +
					'script type="application/ld+json">' +
					JSON.stringify(jsonLd).replaceAll('<', '\\u003c') +
					'<' +
					'/script>'
			: null
	);
</script>

<svelte:head>
	<title>{heading}</title>
	<meta name="description" content={description} />
	<link rel="canonical" href={canonical} />
	<link rel="alternate" hreflang="en" href={enHref} />
	<link rel="alternate" hreflang="fr" href={frHref} />
	<link rel="alternate" hreflang="x-default" href={enHref} />
	<meta name="robots" content="index, follow" />
	<meta property="og:type" content="website" />
	<meta property="og:site_name" content="Regeste" />
	<meta property="og:title" content={heading} />
	<meta property="og:description" content={description} />
	<meta property="og:url" content={canonical} />
	<meta property="og:locale" content={i18n.locale === 'fr' ? 'fr_FR' : 'en_GB'} />
	<!-- One card for the whole site rather than one per page: the image carries the
	     product's claim, not the page's title, and the title beside it is already the
	     page's own. Generated by scripts/build-og-image.mjs. -->
	<meta property="og:image" content={`${CANONICAL_ORIGIN}/og.png`} />
	<meta property="og:image:width" content="1200" />
	<meta property="og:image:height" content="630" />
	<meta property="og:image:alt" content={description} />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:image" content={`${CANONICAL_ORIGIN}/og.png`} />
	<meta name="twitter:title" content={heading} />
	<meta name="twitter:description" content={description} />
	<!-- eslint-disable-next-line svelte/no-at-html-tags -->
	{@html ld ?? ''}
</svelte:head>
